language: python
python:
- '3.6'
sudo: true
branches:
  only:
  - master
  - "/\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
install:
- pip install --upgrade pip
- sudo apt-get remove python-google-compute-engine
- pip install -r requirements.txt
- pip install --upgrade pycodestyle
env:
  global:
  - secure: edLz276bMG/JH5sqcCfaDUs5Evq6Cd+lShMfYtldHX4zEDk0xC0xBX5dFQeRvek0Y9W9vPZQMmr+Zos2G+Yj/+B2e1VJ3xxfYtd6U6NZaD4itjkRDHEl8rW+9j7GFQ1ScSYrgjfxN6/JY3y0D0m8ExxLC7g4BRIAQ7vby1bfaVkUuHhUG45DGT83bNU2ngWLOp5/sKabvOddGE3GJXh+bI7H5dRnsWld/Im6WOWuTmVTA0QR3YG0jrkxQ6tYnBEo5GwNS3tun32r0Z6MDhV6KHannisfXPQ4T266+aMPSulZB1H24h+LrlxZ7cJjRy8lrWmh4e+NAlGdkSzVzZgjEKp659nrS5Lh9oTEXuuo6l1rDQqvkN72UFD7BkhBDVM2sG85TNQPGoQ3Un3y+4rQN/sOVQoWvTAaNhbPuV/0av8IQIa1WzF0KJRXRvFHWK6LggoWnuKwMuiSHOE0ndUNhkw3IZjgmjqICFiniOjHdd9orr7HQqvSTeyhVllfUiHm03UbXkum5yvuQKAw2ElIiMEsq01tDUOzVv+TtyXnd2dylJcWtwqRvUHOuna16yZm7051LWlVSSdwcDb18KjH5RGDoC4o8JvDrgvpn+596VyDieq0knLnisp7r0TCq3gQCN+mBthfwc1WRr7cwaB3Rq3qkmHLgGfHf89jRcYRyKc=
import:
- source: streamr-dev/travis-ci:aws-staging-secrets.yml@master
jobs:
  include:
  - stage: Tests
    name: lint
    script:
    - pip install pycodestyle
    - pycodestyle --max-line-length=120 index.py
  - stage: Tests
    name: Unit Tests
    script:
    - pip install -r requirements.txt
    - python -m unittest discover -s ./tests -t ./tests
  - stage: Deploy Staging
    name: Deploy to Staging
    script:
    - zip -r latest.zip index.py
    - mkdir upload
    - mv latest.zip upload
    deploy:
    - provider: s3
      access_key_id: "$ACCESS_KEY_STG"
      secret_access_key: "$SECRET_ACCESS_KEY_STG"
      bucket: eu-west-1-stg-streamr-vault
      upload-dir: lambda/memory-widget-updater
      local-dir: "$TRAVIS_BUILD_DIR/upload"
      acl: private
      region: eu-west-1
      skip_cleanup: true
    - provider: lambda
      access_key_id: "$ACCESS_KEY_STG"
      secret_access_key: "$SECRET_ACCESS_KEY_STG"
      function_name: eu-west-1-stg-memory-widget-updater
      region: eu-west-1
      handler_name: lambda_handler
      runtime: python3.7
      role: arn:aws:iam::$STG_ACCOUNT_ID:role/eu-west-1-stg-memory-widget-updater-role
